// generated by `sqlx migrate build-script`
fn main() {
    // trigger recompilation when a new migration is added
    println!("cargo:rerun-if-changed=migrations");

    // trigger recompilation when frontend files change
    println!("cargo:rerun-if-changed=app/docuseal/src");
    println!("cargo:rerun-if-changed=app/docuseal/public");
    println!("cargo:rerun-if-changed=app/docuseal/package.json");

    // Setup PDFium library
    setup_pdfium();

    // Optional: You can add database setup checks here if needed
    // But be careful as build.rs runs during compilation

    // Build the frontend
    build_frontend();
}

fn setup_pdfium() {
    use std::env;
    
    // For pdfium-render with static feature, it will handle downloading
    // the correct pdfium library automatically during build
    // Just ensure we're using the static feature in Cargo.toml
    
    println!("cargo:warning=PDFium setup: using static linking");
    
    // Set environment variable to use static linking
    if env::var("PDFIUM_DYNAMIC_LIB_PATH").is_err() {
        println!("cargo:warning=Using bundled static PDFium library");
    }
}

fn build_frontend() {
    use std::process::Command;
    use std::env;

    // Get the current directory
    let current_dir = env::current_dir().unwrap();
    
    // Path to the frontend directory
    let frontend_dir = current_dir.join("app").join("docuseal");
    
    println!("cargo:warning=Building frontend...");
    
    // Run npm build in the frontend directory
    let status = Command::new("npm")
        .arg("run")
        .arg("build")
        .current_dir(&frontend_dir)
        .status()
        .expect("Failed to run npm build");
    
    if !status.success() {
        panic!("Frontend build failed");
    }
    
    println!("cargo:warning=Frontend build completed successfully");
}
